### ISSUE TITLE
ppm-prototype is linked to from divviup.org but cannot be built locally due to absolute path

### ISSUE THREAD

**Issue by jbr** [divviup/ppm-prototype#3]
:wave: Hi! This repository cannot be built against libprio-rs github head and the cargo.toml [links to an absolute local path](https://github.com/divviup/ppm-prototype/blob/main/Cargo.toml#L22). Should it be pinned to the github sha [that is commented out](https://github.com/divviup/ppm-prototype/blob/main/Cargo.toml#L21)? Is this repository still relevant? If not, should it be removed from [the open source section of the website](https://github.com/divviup/website/blob/main/content/en/about.html#L82)?

**Comment by tgeoghegan** [comment]
Thanks for reporting this! I've just pushed some changes that pull in `prio 0.7.0` and clean up remaining build and test issues. Please let me know if this is working on your end now and we can close this.

**Comment by jbr** [comment]
Successfully built locally now!
